language: python

python:
  - "3.6"

cache:
  - pip

install:
  - pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
  
script:
  - python3 -u script.py $TRAVIS_PULL_REQUEST
  - python3 -u script.py $TRAVIS_PULL_REQUEST
  - python3 -u script.py $TRAVIS_PULL_REQUEST
  - python3 -u script.py $TRAVIS_PULL_REQUEST
  - python3 -u script.py $TRAVIS_PULL_REQUEST
  - python3 -u script.py $TRAVIS_PULL_REQUEST


after_script:
  - bash travis_files/deploy.sh
